package org.example;

import java.util.Scanner;
import java.util.stream.IntStream;

public class Main {
    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            System.out.println("Please pass in the grammar filename as a program argument.");
            System.exit(1);
        }
        var fileName = args[0];
        var grammar = Helper.newReadFromFile(fileName);
        var scanner = new Scanner(System.in);
        while (true) {
            System.out.println("Enter input string (q to quit):");
            var input = scanner.nextLine().trim();
            if (input.equals("q")) {
                System.out.println("Exiting...");
                break;
            }
            var inputTerms = Helper.getTermListFromStr(input);
            var table = new CYKTable(Helper.getTermListFromStr(input), grammar);
            table.addBottomRow();
            IntStream.rangeClosed(2, inputTerms.size()).forEach(table::addNonBottomRow);
            var isOrIsNot = table.getAnswer() ? "is" : "is not";
            System.out.println("Input string " + isOrIsNot + " generated by grammar.");
        }
    }
}